[tools]
bat = "latest"
bun = "latest"
chezmoi = "latest"
edit = "latest"
helix = "latest"
lazygit = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
fd = "latest"
fzf = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
ripgrep = "latest"
sd = "latest"
gh = "latest"
zellij = "latest"
atuin = "latest"
