[mgr]
prepend_keymap = [
	{ on = "j", run = "leave", desc = "Back to the parent directory" },
	{ on = "J", run = "back", desc = "Back to previous directory" },
	{ on = "h", run = "arrow next", desc = "Next file" },
	{ on = "H", run = "seek 5", desc = "Seek down 5 units in the preview" },
]

[tasks]
prepend_keymap = [{ on = "h", run = "arrow next", desc = "Next task" }]

[pick]
prepend_keymap = [{ on = "h", run = "arrow next", desc = "Next option" }]

[confirm]
prepend_keymap = [{ on = "h", run = "arrow next", desc = "Next line" }]

[help]
prepend_keymap = [{ on = "h", run = "arrow next", desc = "Next line" }]

[spot]
prepend_keymap = [
	{ on = "j", run = "swipe prev", desc = "Swipe to previous file" },
]

[input]
prepend_keymap = [{ on = "j", run = "move -1", desc = "Move back a character" }]
