keybinding:
  universal:
    nextItem-alt: h
    scrollLeft: J
    prevBlock-alt: j
    scrollDownMain-alt1: H
  commits:
    # <c-h> is not accepted as it's indistinguishable from <backspace>
    moveDownCommit: <backspace>
